version: '3.8'

services:
  pyspark-env:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-pure-container
    network_mode: "service:greenplum-db"
    volumes:
      - ./workspace:/workspace
    depends_on:
      - greenplum-db